export {
  signup,
  verifyEmailOtp,
  resendEmailOtp,
  login,
  refreshSession,
  getCurrentUser,
  logout,
  googleLogin,
  forgotPassword,
  verifyPasswordResetOtp,
  resendPasswordResetOtp,
  resetPassword,
} from "./auth.api";

export { AUTH_ENDPOINTS, AUTH_OTP_LENGTH } from "./auth.constants";

export type {
  AuthMessageResponse,
  AuthTokens,
  ForgotPasswordRequest,
  ForgotPasswordResponse,
  GoogleLoginRequest,
  GoogleLoginResponse,
  LoginRequest,
  LoginResponse,
  LogoutRequest,
  LogoutResponse,
  MeResponse,
  PhoneResponse,
  PublicUser,
  RefreshResponse,
  RefreshSessionRequest,
  ResendEmailOtpRequest,
  ResendEmailOtpResponse,
  ResendPasswordResetOtpRequest,
  ResendPasswordResetOtpResponse,
  ResetPasswordRequest,
  ResetPasswordResponse,
  SignupRequest,
  SignupResponse,
  User,
  UserRole,
  UserStatus,
  VerifyEmailOtpRequest,
  VerifyEmailOtpResponse,
  VerifyPasswordResetOtpRequest,
  VerifyPasswordResetOtpResponse,
} from "./auth.types";

export {
  forgotPasswordRequestSchema,
  googleLoginRequestSchema,
  loginRequestSchema,
  logoutRequestSchema,
  optionalPhoneFieldsSchema,
  phoneFieldsSchema,
  refreshSessionRequestSchema,
  resendEmailOtpRequestSchema,
  resendPasswordResetOtpRequestSchema,
  resetPasswordRequestSchema,
  signupRequestSchema,
  verifyEmailOtpRequestSchema,
  verifyPasswordResetOtpRequestSchema,
} from "./auth.schemas";
