import { calculateDeliveryPricing } from "./pricing";
import {
  buildDefaultTimeline,
  type Delivery,
  type DeliveryFilter,
  type DeliveryStatus,
} from "./types";

const MOCK_PACKAGE_PHOTO =
  "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&h=300&fit=crop";

const MOCK_DRIVER = {
  name: "Rahul Sharma",
  rating: 4.8,
  vehicleType: "Honda Activa",
  vehicleNumber: "MH 12 AB 1234",
  phone: "+91 98765 43210",
  status: "in_transit" as const,
  initials: "RS",
};

export const MOCK_DELIVERIES: Delivery[] = [
  {
    id: "DUTT-1042",
    status: "in_transit",
    statusLabel: "In Transit",
    pickup: { city: "Mumbai", address: "Koramangala, 12th Main Road" },
    dropoff: { city: "Mumbai", address: "Indiranagar, 100 Feet Road" },
    packageType: "Medicine",
    weight: "2.5 kg",
    dimensions: "30 × 20 × 15 cm",
    requirements: ["Handle with care"],
    dateLabel: "Today",
    listTimeLabel: "Today 12:03 PM",
    createdAt: "2026-09-08T08:00:00.000Z",
    estimatedArrival: "12:15 PM",
    driverInitials: "RS",
    selectedService: "FlashDrop",
    thirdPartyCharge: 200,
    pricing: calculateDeliveryPricing(200),
    driver: MOCK_DRIVER,
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    prohibitedItemsConsent: true,
    pickupOtp: "4821",
    deliveryOtp: "7394",
    pickupOtpVerified: true,
    deliveryOtpVerified: false,
    timeline: buildDefaultTimeline("in_transit", {
      pickupOtpVerified: true,
      deliveryOtpVerified: false,
    }),
  },
  {
    id: "DUTT-1041",
    status: "delivered",
    statusLabel: "Delivered",
    pickup: { city: "Mumbai", address: "Andheri West, Link Road" },
    dropoff: { city: "Thane", address: "Ghodbunder Road" },
    packageType: "Documents",
    weight: "0.4 kg",
    dimensions: "30 × 22 × 2 cm",
    requirements: [],
    dateLabel: "Yesterday",
    listTimeLabel: "Yesterday 4:20 PM",
    createdAt: "2026-09-07T10:00:00.000Z",
    estimatedArrival: "Delivered 4:20 PM",
    driverInitials: "RS",
    selectedService: "MoveX",
    thirdPartyCharge: 240,
    pricing: calculateDeliveryPricing(240),
    driver: { ...MOCK_DRIVER, status: "picked_up" },
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    prohibitedItemsConsent: true,
    pickupOtp: "9182",
    deliveryOtp: "3045",
    pickupOtpVerified: true,
    deliveryOtpVerified: true,
    timeline: buildDefaultTimeline("delivered", {
      pickupOtpVerified: true,
      deliveryOtpVerified: true,
    }),
  },
  {
    id: "DUTT-1040",
    status: "delivered",
    statusLabel: "Delivered",
    pickup: { city: "Mumbai", address: "Lower Parel, Senapati Bapat Marg" },
    dropoff: { city: "Navi Mumbai", address: "Vashi, Sector 17" },
    packageType: "Food",
    weight: "5 kg",
    dimensions: "40 × 30 × 25 cm",
    requirements: ["Fragile"],
    dateLabel: "Sep 6, 2026",
    listTimeLabel: "Sep 6, 2026 2:10 PM",
    createdAt: "2026-09-06T09:00:00.000Z",
    estimatedArrival: "Delivered 2:10 PM",
    driverInitials: "AK",
    selectedService: "CityFleet",
    thirdPartyCharge: 185,
    pricing: calculateDeliveryPricing(185),
    driver: {
      name: "Amit Kumar",
      rating: 4.6,
      vehicleType: "Maruti Swift",
      vehicleNumber: "MH 01 CD 5678",
      phone: "+91 91234 56789",
      status: "picked_up",
      initials: "AK",
    },
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    prohibitedItemsConsent: true,
    pickupOtp: "5510",
    deliveryOtp: "8823",
    pickupOtpVerified: true,
    deliveryOtpVerified: true,
    timeline: buildDefaultTimeline("delivered", {
      pickupOtpVerified: true,
      deliveryOtpVerified: true,
    }),
  },
  {
    id: "DUTT-1037",
    status: "in_transit",
    statusLabel: "In Transit",
    pickup: { city: "Mumbai", address: "Powai, Hiranandani Gardens" },
    dropoff: { city: "Mumbai", address: "Goregaon West, Link Road" },
    packageType: "Documents",
    weight: "0.8 kg",
    dimensions: "28 × 22 × 2 cm",
    requirements: [],
    dateLabel: "Today",
    listTimeLabel: "Today 9:15 AM",
    createdAt: "2026-09-08T06:30:00.000Z",
    estimatedArrival: "Estimated 3:30 PM",
    driverInitials: "VK",
    selectedService: "SwiftGo",
    thirdPartyCharge: 165,
    pricing: calculateDeliveryPricing(165),
    driver: {
      name: "Vikram Kulkarni",
      rating: 4.7,
      vehicleType: "TVS Jupiter",
      vehicleNumber: "MH 14 GH 3344",
      phone: "+91 90123 45678",
      status: "in_transit",
      initials: "VK",
    },
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    prohibitedItemsConsent: true,
    pickupOtp: "1234",
    deliveryOtp: "5678",
    pickupOtpVerified: true,
    deliveryOtpVerified: false,
    timeline: buildDefaultTimeline("in_transit", {
      pickupOtpVerified: true,
      deliveryOtpVerified: false,
    }),
  },
  {
    id: "DUTT-1039",
    status: "failed",
    statusLabel: "Failed",
    pickup: { city: "Mumbai", address: "Colaba, Gateway area" },
    dropoff: { city: "Andheri", address: "Andheri East, MIDC" },
    packageType: "Food",
    weight: "1.8 kg",
    dimensions: "25 × 18 × 12 cm",
    requirements: [],
    dateLabel: "Sep 4, 2026",
    listTimeLabel: "Sep 4, 2026 6:40 PM",
    createdAt: "2026-09-04T11:00:00.000Z",
    estimatedArrival: "—",
    driverInitials: "JD",
    selectedService: "SwiftGo",
    thirdPartyCharge: 175,
    pricing: calculateDeliveryPricing(175),
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    timeline: buildDefaultTimeline("failed"),
  },
  {
    id: "DUTT-1038",
    status: "delivered",
    statusLabel: "Delivered",
    pickup: { city: "Mumbai", address: "Worli, Annie Besant Road" },
    dropoff: { city: "Bandra", address: "Bandra West, Hill Road" },
    packageType: "Medicine",
    weight: "3.2 kg",
    dimensions: "35 × 25 × 18 cm",
    requirements: ["Keep upright"],
    dateLabel: "Sep 3, 2026",
    listTimeLabel: "Sep 3, 2026 11:45 AM",
    createdAt: "2026-09-03T07:00:00.000Z",
    estimatedArrival: "Delivered 11:45 AM",
    driverInitials: "PS",
    selectedService: "FlashDrop",
    thirdPartyCharge: 210,
    pricing: calculateDeliveryPricing(210),
    driver: {
      name: "Priya Singh",
      rating: 4.9,
      vehicleType: "TVS Jupiter",
      vehicleNumber: "MH 02 EF 9012",
      phone: "+91 99887 76655",
      status: "picked_up",
      initials: "PS",
    },
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    pickupOtp: "7744",
    deliveryOtp: "2299",
    pickupOtpVerified: true,
    deliveryOtpVerified: true,
    timeline: buildDefaultTimeline("delivered", {
      pickupOtpVerified: true,
      deliveryOtpVerified: true,
    }),
  },
  {
    id: "DUTT-1036",
    status: "delivered",
    statusLabel: "Delivered",
    pickup: { city: "Mumbai", address: "Dadar, Shivaji Park" },
    dropoff: { city: "Mumbai", address: "Chembur, RCF Colony" },
    packageType: "Parcel",
    weight: "1.2 kg",
    dimensions: "20 × 15 × 10 cm",
    requirements: [],
    dateLabel: "Sep 2, 2026",
    listTimeLabel: "Sep 2, 2026 1:05 PM",
    createdAt: "2026-09-02T08:00:00.000Z",
    estimatedArrival: "Delivered 1:05 PM",
    driverInitials: "NK",
    selectedService: "MoveX",
    thirdPartyCharge: 155,
    pricing: calculateDeliveryPricing(155),
    driver: {
      name: "Neha Kapoor",
      rating: 4.5,
      vehicleType: "Honda Activa",
      vehicleNumber: "MH 03 JK 7788",
      phone: "+91 98760 12345",
      status: "picked_up",
      initials: "NK",
    },
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    pickupOtp: "4411",
    deliveryOtp: "9922",
    pickupOtpVerified: true,
    deliveryOtpVerified: true,
    timeline: buildDefaultTimeline("delivered", {
      pickupOtpVerified: true,
      deliveryOtpVerified: true,
    }),
  },
  {
    id: "DUTT-1035",
    status: "delivered",
    statusLabel: "Delivered",
    pickup: { city: "Mumbai", address: "Malad, Link Road" },
    dropoff: { city: "Mumbai", address: "Kandivali East, Western Express Highway" },
    packageType: "Box",
    weight: "4.0 kg",
    dimensions: "45 × 35 × 30 cm",
    requirements: ["Heavy"],
    dateLabel: "Sep 2, 2026",
    listTimeLabel: "Sep 2, 2026 5:40 PM",
    createdAt: "2026-09-02T09:30:00.000Z",
    estimatedArrival: "Delivered 5:40 PM",
    driverInitials: "RM",
    selectedService: "CityFleet",
    thirdPartyCharge: 220,
    pricing: calculateDeliveryPricing(220),
    driver: {
      name: "Ravi Mehta",
      rating: 4.4,
      vehicleType: "Maruti Eeco",
      vehicleNumber: "MH 04 LM 5566",
      phone: "+91 91230 98765",
      status: "picked_up",
      initials: "RM",
    },
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    pickupOtp: "3300",
    deliveryOtp: "8811",
    pickupOtpVerified: true,
    deliveryOtpVerified: true,
    timeline: buildDefaultTimeline("delivered", {
      pickupOtpVerified: true,
      deliveryOtpVerified: true,
    }),
  },
  {
    id: "DUTT-1034",
    status: "delivered",
    statusLabel: "Delivered",
    pickup: { city: "Mumbai", address: "Borivali West, IC Colony" },
    dropoff: { city: "Mumbai", address: "Juhu, JVPD Scheme" },
    packageType: "Documents",
    weight: "0.3 kg",
    dimensions: "25 × 18 × 2 cm",
    requirements: [],
    dateLabel: "Sep 1, 2026",
    listTimeLabel: "Sep 1, 2026 10:20 AM",
    createdAt: "2026-09-01T10:00:00.000Z",
    estimatedArrival: "Delivered 10:20 AM",
    driverInitials: "AS",
    selectedService: "SwiftGo",
    thirdPartyCharge: 145,
    pricing: calculateDeliveryPricing(145),
    driver: {
      name: "Anita Shah",
      rating: 4.8,
      vehicleType: "TVS Jupiter",
      vehicleNumber: "MH 05 NO 1122",
      phone: "+91 99880 11223",
      status: "picked_up",
      initials: "AS",
    },
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    pickupOtp: "2200",
    deliveryOtp: "7700",
    pickupOtpVerified: true,
    deliveryOtpVerified: true,
    timeline: buildDefaultTimeline("delivered", {
      pickupOtpVerified: true,
      deliveryOtpVerified: true,
    }),
  },
  {
    id: "DUTT-1033",
    status: "delivered",
    statusLabel: "Delivered",
    pickup: { city: "Mumbai", address: "Fort, CST area" },
    dropoff: { city: "Mumbai", address: "Matunga, Five Gardens" },
    packageType: "Food",
    weight: "2.1 kg",
    dimensions: "30 × 25 × 15 cm",
    requirements: ["Keep upright"],
    dateLabel: "Sep 1, 2026",
    listTimeLabel: "Sep 1, 2026 3:15 PM",
    createdAt: "2026-09-01T12:00:00.000Z",
    estimatedArrival: "Delivered 3:15 PM",
    driverInitials: "SG",
    selectedService: "FlashDrop",
    thirdPartyCharge: 190,
    pricing: calculateDeliveryPricing(190),
    driver: {
      name: "Sanjay Gupta",
      rating: 4.6,
      vehicleType: "Honda Activa",
      vehicleNumber: "MH 06 PQ 8899",
      phone: "+91 97654 32109",
      status: "picked_up",
      initials: "SG",
    },
    packagePhotoUrl: MOCK_PACKAGE_PHOTO,
    pickupOtp: "1100",
    deliveryOtp: "6600",
    pickupOtpVerified: true,
    deliveryOtpVerified: true,
    timeline: buildDefaultTimeline("delivered", {
      pickupOtpVerified: true,
      deliveryOtpVerified: true,
    }),
  },
];

export function getDeliveryById(id: string): Delivery | undefined {
  return MOCK_DELIVERIES.find((d) => d.id === id);
}

export function getRecentDeliveries(limit = 10): Delivery[] {
  return MOCK_DELIVERIES.slice(0, limit);
}

const IN_TRANSIT_STATUSES: DeliveryStatus[] = [
  "in_transit",
  "picked_up",
  "driver_assigned",
  "booked",
];

export function filterDeliveries(
  deliveries: Delivery[],
  filter: DeliveryFilter,
): Delivery[] {
  if (filter === "all") return deliveries;
  if (filter === "delivered") {
    return deliveries.filter((d) => d.status === "delivered");
  }
  if (filter === "cancelled") {
    return deliveries.filter((d) => d.status === "cancelled");
  }
  if (filter === "failed") {
    return deliveries.filter((d) => d.status === "failed");
  }
  return deliveries.filter((d) => IN_TRANSIT_STATUSES.includes(d.status));
}

export { deliveryRoutePath, deliveryTrackingPath } from "./paths";
